/**
 * Machine-readable answer key for exam.js (must match serialization order on each page).
 * Source: Python Questions and Answers.txt (project root). Drag-and-drop-only pages are null.
 */
(function () {
  window.EXAM_ANSWER_KEY = {
    q1: ["False", "False", "True", "True"],
    q2: ['== "n":', '== "Sunday":', '== "Thursday":'],
    q3: ["1"],
    q4: null,
    q5: ["0,3"],
    q6: ["1", "0", "1"],
    q7: ["if a >= 0:", "else:", "if a % 2 == 0:", "else:"],
    q8: ["while", "break", "index += 1"],
    q9: ["if grade >= 90:", "elif grade >= 80:", "elif grade >= 70:", "elif grade >= 65:"],
    q10: ["2"],
    q11: ["1", "0", "0"],
    q12: ["if", "if", "elif", "elif", "and", "else:", "else:"],
    q13: ["0,3"],
    q14: ["3"],
    q15: [
      'triple double qoute (""")',
      "Immediately after the function header",
      "print(cube.__doc__)",
    ],
    q16: [
      "if numerator is None or denominator is None:",
      "elif denominator == 0:",
    ],
    q17: ["3"],
    q18: ["0,2"],
    q19: null,
    q20: ["0,3"],
    q21: ["3"],
    q22: ["0,3"],
    q23: ["for col in range(2, 13):", "for row in range(2, 13):"],
    q24: ["2"],
    q25: ["Config1Config2", "Config1"],
    q26: null,
    q27: ["while(index < 10):", "if numbers[index] == 6:"],
    q28: ["while", "for", "in"],
    q29: null,
    q30: [
      "now = datetime.datetime.now()",
      'today = now.strftime("%A")',
      "daysLeft = 6 - now.weekday()",
    ],
    q31: null,
    q32: ["0", "0", "0", "1"],
    q33: ["int and string", "string", "Mismatched data types(s)"],
    q34: ["assertEqual(a, b)", "assertIs(a, b)", "assertIn(a, b)"],
    q35: ["6", "5"],
    q36: null,
    q37: ["0", "0", "1", "1"],
    q38: [
      'float(input("Enter next rating(1-5, -1 for done)"))',
      'print("The average star rating for the new coffee is "',
      "format(average,'.2f'))",
    ],
    q39: null,
    q40: ["(len(employee_pay)):", "sum / count"],
    q41: ["3"],
    q42: ["0,5"],
    q43: ["0,2"],
    q44: ["word in word_list:", "letter in word:"],
    q45: ["0", "1", "0"],
    q46: null,
    q47: ["0", "1", "0", "0"],
    q48: ["0", "1", "1", "0"],
    q49: null,
    q50: ["open('myFile.txt', 'a')", "file.write"],
    q51: ["0"],
    q52: ["2"],
    q53: ["if numList == alphaList:", "else:"],
    q54: ["try:", "except:"],
    q55: ["2"],
    q56: ["3"],
    q57: null,
  };
})();
